name: 博客自动构建

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检查代码
      uses: actions/checkout@v2

    - name: 设置Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: 安装依赖
      run: |
        npm install --force
        npm install --save hexo-theme-fluid

    - name: 构建
      run: |
        npm run build

    - name: 推送
      run: |
        git config --global user.email "1216692740@qq.com"
        git config --global user.name "blockhaity"
        git clone --branch=gh-pages https://github.com/BlockHaity/BlockHaity.github.io.git output
        rm -rf ./output/*
        cp -rf ./public/* ./output/
        cd ./output/
        git add .
        git commit -m "构建并推送（Action）"
        git push origin gh-pages

