name: 博客自动构建

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检查代码
      uses: actions/checkout@v2

    - name: 设置Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: 安装依赖
      run: |
        npm install --force
        npm install hexo-cli -g
        npm install --save hexo-theme-fluid

    - name: 构建
      run: |
        hexo clean
        hexo g

    - name: 推送
      run: |
        git config --global user.email "1216692740@qq.com"
        git config --global user.name "blockhaity"
        hexo d

