name: Hexo Deploy to gh-pages Branch

on:
  push:
    branches:
      - main  # 触发条件，当 main 分支有 push 事件时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2  # 检出代码

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # 选择 Node.js 版本

    - name: Install Dependencies
      run: npm install  # 安装 Hexo 依赖

    - name: Hexo Generate
      run: npm run build  # 构建 Hexo 静态文件

    - name: Deploy to gh-pages Branch
      run: |
        # 配置 git 用户信息
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # 切换到 HTML 分支
        git checkout -b gh-pages

        # 清除当前分支内容
        git rm -rf .

        # 复制生成的静态文件到 HTML 分支
        cp -r ./public/* .

        # 添加所有文件到 git
        git add .

        # 提交更改
        git commit -m "Update HTML branch with latest build"

        # 推送到远程 HTML 分支
        git push origin gh-ages --force

  build-and-depoly-to-ftp:
    runs-on: ubuntu-latest
    steps:
    - name: Delete files in wwwroot directory on FTP server
      uses: StephanThierry/ftp-delete-action@v2.1
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteFiles: "*" 
        remoteDirectories: "."
      
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Hexo Generate
      run: npm run build

    - name: Push files to wwwroot directory on FTP server
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./public  # 指定本地要上传的目录，根目录'.'表示仓库根目录
        remoteDir: /  # 指定FTP服务器上的远程目录