name: Hexo Deploy

on:
  push:
    branches:
      - main # 触发条件，当 main 分支有 push 事件时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2 # 检出代码

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "24" # 选择 Node.js 版本

      - name: Install Dependencies
        run: npm install # 安装 Hexo 依赖

      - name: Install argon theme
        run: |
          git clone https://github.com/blockhaity/hexo-theme-argon.git themes/argon

      - name: Hexo Generate
        run: npm run build # 构建 Hexo 静态文件

      - name: Run Script
        run: python3 script.py # 运行 Python 脚本

      - name: Set Git information # 设置git信息
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and Push
        run: |
          # 清理主题
          git rm -rf themes/argon

          # 手动获取 gh-pages 分支引用
          git fetch origin gh-pages:refs/remotes/origin/gh-pages

          # 创建并切换分支
          git switch -f -c gh-pages origin/gh-pages

          # 清空分支内容
          git rm -rf .

          # 复制构建产物
          cp -r public/* .

          # 添加、提交
          git add .
          git commit -m "Deploy to GitHub Pages"

          # 强制推送
          git push --force origin gh-pages

    # - name: Deploy to FTP Server
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     server: ${{ secrets.FTP_HOST }}  # FTP 服务器地址
    #     username: ${{ secrets.FTP_USERNAME }}  # FTP 用户名
    #     password: ${{ secrets.FTP_PASSWORD }}  # FTP 密码
    #     local-dir: ./
    #     server-dir: /wwwroot/
    #     dangerous-clean-slate: true  # 清空服务器目录
